title: JH'Log
name: "Junhui's Tech Blog"
author: Junhui Zhang
twitter_username: junhuizhang5
baseurl: "/jhz-log"
description: Document my learning notes.
profile_url: "https://jacksonhacker.github.io/"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
